package pw.aru.app.fate.exports

import pw.aru.app.fate.data.provider.SQLiteServantProvider
import pw.aru.app.fate.data.Servant
import pw.aru.app.fate.data.Servant.Companion.EMPTY_BYTE_ARRAY
import pw.aru.app.fate.data.ServantClass

fun main() {
    addToDb(
        """AdvCorvoArcher""",
        """Victorius Corvus""",
        """Magikia""",
        """Humano""",
        """Archer""",
        "",
        0,
        "",
        """Arco do Persona""",
        """Um arco composto, criado a base da sua personalidade""",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        """Persona Shot""",
        """Corvo se clona quantas vezes conseguir, ou até não ter mais mana, e pode dar até 3 chuvas de tiros."""
    )
    addToDb(
        """AdvCorvoCaster""",
        """Victorius Corvus""",
        """Magikia""",
        """Humano""",
        """Caster""",
        "",
        0,
        "",
        """Persona""",
        """Espírito Invocado a base da sua própria personalidade.
O persona defende quem o invocou e quem o servo mandar proteger, além de ter habilidades com arco.""",
        "",
        "",
        "",
        "",
        """"Eu sou Diva"""",
        """Sensualizando com seu corpo, Dio conquista fãs e amantes, podendo transformar inimigos de nível baixo em aliados fiéis ao Divador.""",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """AdvDioAssassin""",
        """Dio Brando""",
        """Magikia""",
        """Vampiro""",
        """Assassin""",
        """195cm 100kg
Usando Jaqueta
Relativamente Calmo""",
        9,
        """Blood/Clock-based""",
        """Za Warudo""",
        """Espírito Pugilista que aproveita das brechas do tempo pra socar múltiplas vezes em um único ataque.""",
        """Estoque Infinito de Facas""",
        """Facas de Arremesso.
Quantidade Virtualmente Infinita.
Fonte das facas desconhecida.""",
        """ROAD-ROLLER-DA""",
        """Invoca um FUDENDO BANGUE DO INFERNO de QUALQUER DIMENSÃO.
O Road-Roller invocado é arremessável.""",
        """Necromancia Vampiresca""",
        """Após consumir todo o sangue dos inimigos, ele se tornam "servos" mortos-vivos do servo.""",
        """<nenhum>""",
        "",
        "",
        """"TOKI WO TOMARE!"""",
        """(Requer Za Warudo)
Para o Tempo por 30s.
Servo, Za Warudo, Mestre e Aliados não são afetados."""
    )
    addToDb(
        """AdvDioBeserker""",
        """Dio Brando""",
        """Magikia""",
        """Vampiro""",
        """Beserker""",
        """195cm 100kg
Sem Jaqueta
Pistola""",
        9,
        """Blood/Clock-based""",
        """Za Warudo""",
        """Espírito Pugilista que aproveita das brechas do tempo pra socar múltiplas vezes em um único ataque.""",
        """Manoplas""",
        """Manoplas principais do Dio para fazer combo de soco.
Os socos dão bônus contra anjos e demônios.""",
        """ROAD-ROLLER-DA""",
        """Invoca um FUDENDO BANGUE DO INFERNO de QUALQUER DIMENSÃO.
O Road-Roller invocado é arremessável.""",
        """Necromancia Vampiresca""",
        """Após consumir todo o sangue dos inimigos, ele se tornam "servos" mortos-vivos do servo.""",
        """<nenhum>""",
        "",
        "",
        """"TOKI WO TOMARE!"""",
        """(Requer Za Warudo)
Para o Tempo por 30s.
Servo, Za Warudo, Mestre e Aliados não são afetados."""
    )
    addToDb(
        """AdvDioCaster""",
        """Dio Brando""",
        """Magikia""",
        """Vampiro""",
        """Caster""",
        """195cm 100kg
Usando Terno
Relativamente Calmo""",
        9,
        """Blood/Clock-based""",
        """Za Warudo c/Manoplas""",
        """Espírito Pugilista que aproveita das brechas do tempo pra socar múltiplas vezes em um único ataque.
Manoplas dão bônus contra anjos.""",
        """Hidden Blade""",
        """Manoplas principais do Dio, que tem uma Hidden Blade.
Tanto socos quanto a Hidden Blade dão bônus contra anjos e demônios""",
        """ROAD-ROLLER-DA""",
        """Invoca um FUDENDO BANGUE DO INFERNO de QUALQUER DIMENSÃO.
O Road-Roller invocado é arremessável.""",
        """"Eu sou Diva"""",
        """Sensualizando com seu corpo, Dio conquista fãs e amantes, podendo transformar inimigos de nível baixo em aliados fiéis ao Divador.""",
        """<nenhum>""",
        "",
        "",
        """"TOKI WO TOMARE!"""",
        """(Requer Za Warudo)
Para o Tempo por 30s.
Servo, Za Warudo, Mestre e Aliados não são afetados."""
    )
    addToDb(
        """AdvGuildeonArcher""",
        """Guildeon Vainheart""",
        """AdvWorld""",
        """Humano""",
        """Archer""",
        """175cm 79kg
Com capa""",
        8,
        """Doppelganger/Dark-based""",
        """Magical Magnum""",
        """Pistola que atira projéteis .44 feitos de qualquer elemento mágico.""",
        """Double Magical Submachinegun""",
        """Roubadas de um clã que ele não foi com a cara, isso permite dar 4 tiros pelo preço de 1 tiro de pistola.""",
        """Perfect Shot""",
        """Cria micro-alterações no espaço-tempo para que, caso um projétil seja disparado IMEDIATAMENTE após essa skill, seja virtualmente impossível de errar os alvos.""",
        """Perfect Luck""",
        """Tendo como alvo uma ação de sorte e ativando essa magia, cria-se micro-alterações no espaço-tempo deformando a sorte para que esta esteja em favor da ação em mente.""",
        """<nenhum>""",
        "",
        """Não recebe dano de Trevas
Sem Shinobu""",
        """Infinite Shot""",
        """Pausa o tempo e permite dar TANTOS TIROS QUANTO FOREM POSSÍVEIS até toda a Mana disponível pra tiro acabar."""
    )
    addToDb(
        """AdvGuildeonAssassin""",
        """Guildeon Vainheart""",
        """AdvWorld""",
        """Humano""",
        """Assassin""",
        """175cm 79kg
Sem capa""",
        8,
        """Doppelganger/Dark-based""",
        """Magical Magnum""",
        """Pistola que atira projéteis .44 feitos de qualquer elemento mágico.""",
        """Rainbow Blade""",
        """Katana que permite ataques de dentro da sombra. A lâmina é arco-íris normalmente porém fica invisível dentro de uma sombra.""",
        """Perfect Shot""",
        """Cria micro-alterações no espaço-tempo para que, caso um projétil seja disparado IMEDIATAMENTE após essa skill, seja virtualmente impossível de errar os alvos.""",
        """Perfect Luck""",
        """Tendo como alvo uma ação de sorte e ativando essa magia, cria-se micro-alterações no espaço-tempo deformando a sorte para que esta esteja em favor da ação em mente.""",
        """<nenhum>""",
        "",
        """Não recebe dano de Trevas
Sem Shinobu""",
        """ShadowWalker""",
        """Permite ao Guildeon entrar e andar nas sombras da cidade, como também pegar carona na sombra de pessoas."""
    )
    addToDb(
        """AdvGuildeonCaster""",
        """Guildeon Vainheart""",
        """AdvWorld""",
        """Humano""",
        """Caster""",
        """175cm 79kg
Com capa""",
        8,
        """Doppelganger/Dark-based""",
        """Magical Magnum""",
        """Pistola que atira projéteis .44 feitos de qualquer elemento mágico.""",
        """Shinobu<tick>s Hidden Blade""",
        """Guildeon tem uma vampira na sombra dele que pode dar ataques físicos com uma espada invísivel que suga o sangue dos inimigos.""",
        """Perfect Shot""",
        """Cria micro-alterações no espaço-tempo para que, caso um projétil seja disparado IMEDIATAMENTE após essa skill, seja virtualmente impossível de errar os alvos.""",
        """Perfect Luck""",
        """Tendo como alvo uma ação de sorte e ativando essa magia, cria-se micro-alterações no espaço-tempo deformando a sorte para que esta esteja em favor da ação em mente.""",
        """<nenhum>""",
        "",
        """Não recebe dano de Trevas
Companion: Shinobu, na sombra dele""",
        """Pincel da Realidade""",
        """Pincel que pode PERMANENTEMENTE alterar a realidade. O pincel segue a regra de troca equivalente e permite destruir ou criar qualquer coisa."""
    )
    addToDb(
        """AdvGuildeonRider""",
        """Guildeon Vainheart""",
        """AdvWorld""",
        """Humano""",
        """Rider""",
        """175cm 79kg
Com capa""",
        8,
        """Doppelganger/Dark-based""",
        """Magical Magnum""",
        """Pistola que atira projéteis .44 feitos de qualquer elemento mágico.""",
        """Shinobu<tick>s Hidden Blade""",
        """Guildeon tem uma vampira na sombra dele que pode dar ataques físicos com uma espada invísivel que suga o sangue dos inimigos.""",
        """Perfect Shot""",
        """Cria micro-alterações no espaço-tempo para que, caso um projétil seja disparado IMEDIATAMENTE após essa skill, seja virtualmente impossível de errar os alvos.""",
        """Perfect Luck""",
        """Tendo como alvo uma ação de sorte e ativando essa magia, cria-se micro-alterações no espaço-tempo deformando a sorte para que esta esteja em favor da ação em mente.""",
        """Moto 3Dragons RGB""",
        """Moto feita a partir de 3 dragões mecânicos que vira drone.
Chega a incríveis 500km/h""",
        """Não recebe dano de Trevas
Companion: Shinobu, na sombra dele""",
        """Weightless Touch""",
        """Guildeon pode anular o peso dele e de qualquer coisa que ele segure, como por exemplo a Moto dele."""
    )
    addToDb(
        """AdvHitsugaiaRider""",
        """Toshiro Hitsugaia""",
        """Magikia""",
        """Meio-Dragão de Gelo""",
        """Rider""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """AdvJojoCaster""",
        """Jotaro Kujo""",
        """Magikia""",
        """Meio-Demônio""",
        """Caster""",
        """195cm 85kg""",
        6,
        """<nenhum em especial>""",
        """Star Platinum""",
        """Espírito Pugilista que dá soco por segundo pra caralho.""",
        """Estoque Infinito de Facas""",
        """Facas de Arremesso.
Quantidade Virtualmente Infinita.
Fonte das facas desconhecida.""",
        """Time Counter""",
        """Permite a Jotaro "entrar" em "Time Stops", mesmo não sendo aliado de quem parou o tempo.""",
        """"Eu sou Diva"""",
        """Sensualizando com seu corpo, Dio conquista fãs e amantes, podendo transformar inimigos de nível baixo em aliados fiéis ao Divador.""",
        """<nenhum>""",
        "",
        "",
        """Universe Stop""",
        """Por 30s, congela tudo que está no seu campo de visão."""
    )
    addToDb(
        """AdvSatyaCaster""",
        """Satya Lindholm""",
        """Magikia""",
        """Dragão de Luz e Trevas""",
        """Caster""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """AdvSatyaSaber""",
        """Satya Lindholm""",
        """Magikia""",
        """Dragão de Luz e Trevas""",
        """Saber""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """IskCorvoSaber""",
        """Victorius Corvus Primarius""",
        """ProjektIsekai""",
        """Humano""",
        """Saber""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """MdvGuildeonAssassin""",
        """Guildeon Vainheart""",
        """AdvMedieval""",
        """Lorde Demônio""",
        """Assassin""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """MdvGuildeonCaster""",
        """Guildeon Vainheart""",
        """AdvMedieval""",
        """Lorde Demônio""",
        """Caster""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """MdvVainCaster""",
        """Vain""",
        """AdvMedieval""",
        """Demônio""",
        """Caster""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcAruArcher""",
        """Aru""",
        """Universo ADV""",
        """Anja""",
        """Archer""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcAruAssassin""",
        """Aru""",
        """Universo ADV""",
        """Anja""",
        """Assassin""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcAruCaster""",
        """Aru""",
        """Universo ADV""",
        """Anja""",
        """Caster""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcAruRuler""",
        """Aru""",
        """Universo ADV""",
        """Anja""",
        """Ruler""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcDavidCaster""",
        """David Lotus Nataniel""",
        """Magikia""",
        """Humano""",
        """Caster""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcDavidRuler""",
        """David Lotus Nataniel""",
        """Magikia""",
        """Humano""",
        """Ruler""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcFafnirBeserker""",
        """Fafnir""",
        """Universo ADV""",
        """Dragão de Fogo""",
        """Beserker""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcHyourinmaruArcher""",
        """Hyourinmaru""",
        """Magikia""",
        """Dragão de Gelo""",
        """Archer""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcHyourinmaruBeserker""",
        """Hyourinmaru""",
        """Magikia""",
        """Dragão de Gelo""",
        """Beserker""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcHyourinmaruLancer""",
        """Hyourinmaru""",
        """Magikia""",
        """Dragão de Gelo""",
        """Lancer""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcHyourinmaruRuler""",
        """Hyourinmaru""",
        """Magikia""",
        """Dragão de Gelo""",
        """Ruler""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcKazeAssassin""",
        """Kaze no Shinobu""",
        """AdvWorld""",
        """Vampira""",
        """Assassin""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcKiLancer""",
        "",
        """AdvMedieval""",
        """Lorde Demônio""",
        """Lancer""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcLinceArcher""",
        "",
        """AdvMedieval""",
        """Meio-Demônio""",
        """Archer""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcLinceLancer""",
        "",
        """AdvMedieval""",
        """Meio-Demônio""",
        """Lancer""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcLuciAssassin""",
        "",
        """AdvWorld""",
        "",
        """Assassin""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcLuciiArcher""",
        """Lucii Starstream""",
        """Universo ADV""",
        "",
        """Archer""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcLuciiRuler""",
        """Lucii Starstream""",
        """Universo ADV""",
        "",
        """Ruler""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcLuciiSaber""",
        """Lucii Starstream""",
        """Universo ADV""",
        "",
        """Saber""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcMikailaCaster""",
        "",
        """AdvWorld""",
        """Humana""",
        """Caster""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcMochiyukiBeserker""",
        """Mochiyuki Arihara""",
        """Universo ADV""",
        """Hyperhuman (Negative: Hyperdestructive)""",
        """Beserker""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcMochiyukiRider""",
        """Mochiyuki Arihara""",
        """Universo ADV""",
        """Hyperhuman (Negative: Hyperdestructive)""",
        """Rider""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcMochiyukiSaber""",
        """Mochiyuki Arihara""",
        """Universo ADV""",
        """Hyperhuman (Negative: Hyperdestructive)""",
        """Saber""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcMochizukiArcher""",
        """Mochizuki Arihara""",
        """Universo ADV""",
        """Hyperhuman (Positive: Hyperactive)""",
        """Archer""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcMochizukiCaster""",
        """Mochizuki Arihara""",
        """Universo ADV""",
        """Hyperhuman (Positive: Hyperactive)""",
        """Caster""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcMochizukiRider""",
        """Mochizuki Arihara""",
        """Universo ADV""",
        """Hyperhuman (Positive: Hyperactive)""",
        """Rider""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcMochizukiSaber""",
        """Mochizuki Arihara""",
        """Universo ADV""",
        """Hyperhuman (Positive: Hyperactive)""",
        """Saber""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcNatiArcher""",
        """Nati Brando""",
        """Magikia""",
        """Humano""",
        """Archer""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcNatiAssassin""",
        """Nati Brando""",
        """Magikia""",
        """Humano""",
        """Assassin""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcNatiRider""",
        """Nati Brando""",
        """Magikia""",
        """Humano""",
        """Rider""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcPendragonArcher""",
        """Pendragon""",
        """Universo ADV""",
        """Meio-dragão""",
        """Archer""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcPendragonSaber""",
        """Pendragon""",
        """Universo ADV""",
        """Meio-dragão""",
        """Saber""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcRyuArcher""",
        "",
        """AdvMedieval""",
        """Meio-demônio""",
        """Archer""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcRyuCaster""",
        "",
        """AdvMedieval""",
        """Meio-demônio""",
        """Caster""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcSoraArcher""",
        """Sora""",
        """Universo ADV""",
        """Anja""",
        """Archer""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcSoraAssassin""",
        """Sora""",
        """Universo ADV""",
        """Anja""",
        """Assassin""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcSoraCaster""",
        """Sora""",
        """Universo ADV""",
        """Anja""",
        """Caster""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcViktorArcher""",
        """Viktor Lotus Nataniel""",
        """Magikia""",
        """Humano""",
        """Archer""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcViktorBeserker""",
        """Viktor Lotus Nataniel""",
        """Magikia""",
        """Humano""",
        """Beserker""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcViktorCaster""",
        """Viktor Lotus Nataniel""",
        """Magikia""",
        """Humano""",
        """Caster""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcViktorRider""",
        """Viktor Lotus Nataniel""",
        """Magikia""",
        """Humano""",
        """Rider""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcYashiCaster""",
        """Yashi Lionheart Skyfer""",
        """Universo ADV""",
        """Humano""",
        """Caster""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcYashiLancer""",
        """Yashi Lionheart Skyfer""",
        """Universo ADV""",
        """Humano""",
        """Lancer""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcYashiRider""",
        """Yashi Lionheart Skyfer""",
        """Universo ADV""",
        """Humano""",
        """Rider""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcYashiSaber""",
        """Yashi Lionheart Skyfer""",
        """Universo ADV""",
        """Humano""",
        """Saber""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcYetCaster""",
        """Yet""",
        """Universo ADV""",
        "",
        """Caster""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcZihiraCaster""",
        """Zihira""",
        """Universo ADV""",
        """Metamorfa""",
        """Caster""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
    addToDb(
        """npcZihiraSaber""",
        """Zihira""",
        """Universo ADV""",
        """Metamorfa""",
        """Saber""",
        "",
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    )
}

val servantProvider = SQLiteServantProvider()

fun addToDb(
    fateID: String, name: String, origin: String, race: String,
    type: String, description: String, stars: Int, catalyst: String,
    weapon1: String, weapon1Desc: String, weapon2: String, weapon2Desc: String,
    skill1: String, skill1Desc: String, skill2: String, skill2Desc: String,
    mount: String, mountDesc: String, extras: String, noblePhantasm: String, noblePhantasmDesc: String
) {
    val servant = Servant(
        fateID, name, EMPTY_BYTE_ARRAY, "", origin, race,
        ServantClass.valueOf(type.toUpperCase()), description, stars, catalyst,
        weapon1, weapon1Desc, weapon2, weapon2Desc,
        skill1, skill1Desc, skill2, skill2Desc,
        mount, mountDesc, extras, noblePhantasm, noblePhantasmDesc
    )

    servantProvider.update(servant)
}
